/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './socket-io.module';
class SocketIoModuleInjector extends import0.ɵNgModuleInjector<import1.SocketIoModule> {
  _SocketIoModule_0:import1.SocketIoModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.SocketIoModule {
    this._SocketIoModule_0 = new import1.SocketIoModule();
    return this._SocketIoModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.SocketIoModule)) { return this._SocketIoModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SocketIoModuleNgFactory:import0.NgModuleFactory<import1.SocketIoModule> = new import0.NgModuleFactory<any>(SocketIoModuleInjector,import1.SocketIoModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovUGVyc29uYWwvbmd4LXNvY2tldC1pby9zcmMvc29ja2V0LWlvLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9QZXJzb25hbC9uZ3gtc29ja2V0LWlvL3NyYy9zb2NrZXQtaW8ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
